### ISSUE TITLE
Migrating to SEF 7.1

### ISSUE THREAD

**Issue by sith-on-mars** [beppegoodoldrebel/SEF_FR#27]
SEF just release the [7.1 upgrade](https://www.moddb.com/mods/swat-elite-force/downloads/swat-elite-force-v7-v71-upgrade) without announcement. Would you consider migrate SEF_FR to the latest SEF version?

**Comment by beppegoodoldrebel** [comment]
Most of the 7.1 features are already in 0.65 as I passed commits to my code.

**Comment by sith-on-mars** [comment]
Interesting! Does that mean SEF FR serves as the experiment for SEF from a certain point of view?

**Comment by beppegoodoldrebel** [comment]
Yes and the other way around too... for example I fixed the Cs gas crash and created a commit in SEF.
