### ISSUE TITLE
Rarely happening  GP fault

### ISSUE THREAD

**Issue by haze1986** [beppegoodoldrebel/SEF_FR#33]
No Label

Crash Time: 10/08/22 08:10:34

OS: Windows NT 6.2 (Build: 9200)
CPU: AuthenticAMD Unknown processor @ 3603 MHz with 2047MB RAM
Video: NVIDIA GeForce GTX 1660 Ti (1694)

UserName: Hei
ComputerName: HAZE
Application location: D:\SWAT 4\ContentExpansion\System\

SWAT Build Number: 0.67

Access Violation caused General protection fault!

History: UAI_RunnableAction::ProcessState <- action->ProcessState ['RotateTowardActorAction SP-Warehouse.RotateTowardActorAction62'] <- UAI_Resource::ProcessState <- APawn::UpdateMovementAI <- ASwatPawn::TickSpecial <- ASwatAI::TickSpecial [OfficerRedOne1 - Location: (-827.065796, 5439.993652, 248.000000)] <- AActor::Tick [Actor: 'OfficerRedOne1' Actor->bDeleteMe: FALSE] <- ASwatRagdollPawn::Tick <- TickAllActors <- ULevel::Tick [(NetMode=0)] <- TickLevel <- UGameEngine::Tick <- UpdateWorld <- MainLoop->GenerateExtraCrashInfo [(GLevel: 'myLevel' PendingLevel: '(NULL)' NetMode: 'NM_Standalone'] <- MainLoop

**Comment by beppegoodoldrebel** [comment]
I assume that with Beta 2 and Beta 3 this issue is long gone now.
