### ISSUE TITLE
Improved support for custom campaigns

### ISSUE THREAD

**Issue by induktio** [beppegoodoldrebel/SEF_FR#34]
[Mega Map Pack](https://www.moddb.com/games/swat-4/addons/mega-map-pack) has included an extra feature called Mega Campaign Mod which allows the player to advance through a career consisting of first standard maps and then dozens of custom maps with additional briefings and such.

This feature had to overwrite the base campaign in the game to provide these features and it worked for vanilla TSS and several other older mods such as SSF and HSME. The campaign mod did changes on the following files in ContentExpansion/System:

- Campaign.ini
- DefSwatGUIState.ini
- SwatGame.eng
- SwatGame.int
- SwatGUIState.ini
- SwatMissions.ini
- transient.int

However, Elite Force did extensive changes on the user interface and ini file formats which makes it incompatible with Mega Campaign Mod. Original Elite Force documentation also claimed "Not applicable; SEF includes the features of these mods and/or improves upon them" but this is clearly not the case, because SEF cannot use the floorplans, detailed briefings, and custom loading screens provided by the campaign mod. Also the campaign mod requires the ability to specify custom ordering for specific subset of maps, not just list all the maps on harddrive like SEF does.

It would be preferable to restore the support for custom campaign definitions somehow, but it's not immediately clear how the ini files could be made compatible because the changes are quite extensive in Elite Force mod. The best solution would be to have an ability to use the same ini files than in Campaign Mod, but I'm not sure how simple it would be to use ini files from multiple folders for this purpose. The campaign mod doesn't have to necessarily overwrite the base campaign provided by the game because this was just a solution imposed by the limitation of not doing additional scripting for the mod. In any case, what would be needed here is a well-defined way to setup custom campaigns with detailed briefings, not just list all the maps in the harddrive with no additional info.

**Comment by beppegoodoldrebel** [comment]
I can maybe create another "CareerPath" class that loads a different "Swatmissions.ini" ( that i'll just rename "MegaCamp.ini" ). 
So it will be possible to have separate inis and deal with the GUI eve without it. 

Just an idea for now ... i'll also explore the chanche to have a separate folder so anyone can load their custom campaign.

**Comment by induktio** [comment]
Could it be possible to set it such that the mod could directly use files from ContentExpansion/System even though the game is started from different System folder? It would be very convenient if it could display the same campaign that is present in unmodded TSS as an option in the user interface. For example just allow choice between TSS / FR campaign when creating a new career. Note that not all the files I listed previously need to be used for this purpose, some of them just contain some user interface changes that are not strictly necessary. Only those files that contain the campaign briefing data and the order in which the maps are displayed are necessary. Also I'm not sure what do you mean by renaming that ini file. I think a better approach would be to specify an extra mod folder for the game where it will attempt to load data first, so it will not require renaming ini files.

**Comment by induktio** [comment]
Recently I implemented support for SEF/FR in Mega Campaign Mod v3.0.1. So looks like it was doable after all. There's one possible issue though, and it seems to be also present in the vanilla game. When completing standard missions in the career, the game advances to the next map by incrementing availableIndex in Campaign.ini. When the career gets to the custom maps, it does not seem to be advance to the next map. Not sure what is causing this.

**Comment by beppegoodoldrebel** [comment]
i think the "issue" is here in the GUI. 

https://github.com/beppegoodoldrebel/SEF_FR/blob/a95ddf3eb7bd9bdd542057dcdbce2e482f39da87/Source/Game/SwatGui/Classes/SwatMissionSelectionPanel.uc#L481

CampaignPath=0 ( vanilla campaign ) has just 18 missions so , even if you pass the last one the GUI just load the vanilla class maximum missions. 

That's one of the many  reasons I would have built a new dedicated career path.

**Comment by induktio** [comment]
Is that mission count 20 (vanilla+TSS) hardcoded somewhere in the code? It looks to me it pulls it from the config files instead. Campaign Mod adjusts SwatMissions.ini by increasing the number of missions in SwatGame.SwatVanillaCareerPath. You can see it in MegaCampaingMod_v3.0.1.7z/SEF/System/SwatMissions.ini file. Does the ini file need to be modified in some way? The problem with adding new career paths if I understood what you meant is that the campaign mod SEF version should support both SEF and FR (and BTLA?) at the same time, so we won't need a third version.
