### ISSUE TITLE
SG 552 Commando's punch anims are broken

### ISSUE THREAD

**Issue by A-Randomized-Dude** [beppegoodoldrebel/SEF_FR#35]
"Vanilla" SG 552, Aimpoint and Supressed variants have broken punch anims, plz fix. 

Plus, game is listing 2 supressed SG 552s and they are exactly the same gun.

**Comment by beppegoodoldrebel** [comment]
all is working as intended. 

Gui images are the same for Aimpoint/non Aimpoint classes but they are different weapons in the end.

**Comment by A-Randomized-Dude** [comment]
Yes, you are right, it is just the gui image. 

But punch animations, whats your comment about them? They are broken since sef days (rip sef)
